### ISSUE TITLE
Kopie SEIN

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio#1]
Wil je een kopie maken en deze plaatsen op Cloud VPS of of ODC?
https://gemeente-eersel.pleio.nl/

**Comment by bartjkdp** [comment]
Omdat ze een maatwerk-thema hebben is deze niet beschikbaar. Hoe gaan we hier mee om?

**Comment by ziemerink** [comment]
Nee ze willen dus een kopie zonder hun thema en op basis van het nieuwe responsieve template!

**Comment by bartjkdp** [comment]
Beschikbaar op https://gemeente-eersel.odc.pleio.nl/
