### ISSUE TITLE
Beheerpaneel: Mogelijkheid toevoegen om te kopiëren binnen en tussen omgevingen.

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#10]
VWS wil graag testen met het nieuwe template en daarvoor een test-kopie willen maken.

Daarom willen we een mogelijkheid moeten maken om sites te kopiëren naar dezelfde omgeving en tussen omgevingen. Ik denk dat we de code van het beheer-paneel wat moeten gaan aanpassen, zodat je niet alleen van BIT naar ODC en van BIT naar VPS kan kopiëren, maar ook van ODC naar ODC, van VPS naar VPS van ODC naar VPS en van VPS naar ODC. Idealiter komt er dan 1 beheer-paneel voor beide omgevingen.

**Comment by bartjkdp** [comment]
Eigenlijk zouden we een mogelijkheid moeten maken op sites te kopiëren naar dezelfde omgeving. Ik denk dat we de code van het beheerpaneel wat moeten gaan aanpassen.

**Comment by bartjkdp** [comment]
Het beheerpaneel is grondig herschreven en heeft inmiddels alles ingebouwd. Je kunt nu ook kopieren naar dezelfde omgeving, zie Pleio/pleio-control.
