### ISSUE TITLE
Widgets: De "zoek link" wordt niet altijd getoond

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#11]

**Comment by bartjkdp** [comment]
Ik begrijp niet wat je bedoelt

**Comment by ziemerink** [comment]
Zie bijlage, bij 1 staat een zoek link bij twee is het zelfde ingesteld, maar wordt de zoeklinkzoenklink niet getoond!
<img width="1118" alt="schermafbeelding_2017-12-30_om_12_56_23" src="https://user-images.githubusercontent.com/1875858/34453992-2d37e80c-ed61-11e7-86ce-d4a8ffc5c873.png">

**Comment by bartjkdp** [comment]
Dat komt omdat er geen tags in de widget opgegeven zijn, alleen "uitgesloten tags". De zoekfunctie kan nog niet omgaan met uitgesloten tags.
