### ISSUE TITLE
De teksten bij groepen zijn verdwenen. Normaal kun je een intro tekst van een groep wijzigen. Dit kan nu niet meer. De WYSIWYG is weg.

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#15]
Dit is bij de migratie naar Cloud VPS dit geld voor alle deelsites op Cloud VPS

**Comment by bartjkdp** [comment]
Even de checklist nalopen wat te doen na migratie naar ODC, deze geld ook voor VPS. In dit geval kun je het oplossen door standaard profielveden voor groepen te importeren.

**Comment by ziemerink** [comment]
Top thanks
