### ISSUE TITLE
Afbeeldingen toegevoegd via de WYSYWYG tonen niet, zie afbeelding Op alle deelsite op Cloud VPS

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#16]
![image003](https://user-images.githubusercontent.com/1875858/34531919-5994428c-f0b4-11e7-9004-69747c5adc3c.png)

**Comment by bartjkdp** [comment]
Ik heb het nog eens geprobeerd maar ik kan het niet reproduceren. Is het probleem nog steeds daar?

**Comment by ziemerink** [comment]
Volgens mij is het opgelost!
