### ISSUE TITLE
Notificaties van gebruikers worden niet meegenomen in de migratie naar CloudVPS, met andere woorden gebruikers krijgen na de migratie geen notificaties meer

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#38]

**Comment by bartjkdp** [comment]
Ik heb dit nagekeken. Digest instellingen worden niet meegenomen, notificatie instellingen wel. Het wordt een vrij “lelijke” oplossing om ze alsnog mee te nemen. Wat te doen?

**Comment by ziemerink** [comment]
Kunnen we weer handmatig in de groepen de meldingen aanzetten?

**Comment by bartjkdp** [comment]
Zeker, gewoon de standaard digestinstellingen zoals je ze al kent.

**Comment by ziemerink** [comment]
Standaard stond dit onder "groep bewerken" daar vind ik het nu niet terug!

**Comment by bartjkdp** [comment]
Op welke site zit je te kijken?

**Comment by ziemerink** [comment]
bhv.pleio.nl (Cloud VPS)

**Comment by ziemerink** [comment]
Ja ik wel, als ik bijvoorbeeld i een blog een plaatje wil oploaden!

**Comment by bartjkdp** [comment]
Er ging nog meer mis op CloudVPS (en op ODC). Het systeem dat verantwoordelijk was voor de achtergrondtaken kon helemaal geen mails versturen door een fout. Dat is vanaf heden opgelost waardoor Digest ook weer als verwacht moet werken.

**Comment by bartjkdp** [comment]
Sinds zojuist is het mogelijk om via ```/admin/administer_utilities/notifications``` als beheerder voor alle groepsleden notificaties aan te zetten. Met de knop "Zet auto-notificaties" zorg je dat gebruikers die lid worden van een groep automatisch notificaties ontvangen. Gebruikers ontvangen, wanneer ze 2 uur niet op de site zijn geweest, een mailtje met de nieuwste notificaties.

Daarnaast is het ook mogelijk om een periodiek overzicht in te stellen. Dit is een wekelijks overzicht van content die gebruiker nog niet gezien heeft (los van groepen).
