### ISSUE TITLE
Pleiofile: bestandsnaam ook in de URL zichtbaar maken

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio#4]

**Comment by bartjkdp** [comment]
Geen idee meer wat dit is.

**Comment by ziemerink** [comment]
Vraag van Provincie zie bijlage
[Re Pleio bestanden.pdf](https://github.com/Pleio/pleio/files/1594346/Re.Pleio.bestanden.pdf)

**Comment by bartjkdp** [comment]
Is dit niet al opgelost?

**Comment by bartjkdp** [comment]
Ohnee, niet voor pleiofile, wel voor file_tools denk ik.
