### ISSUE TITLE
k krijg geen HTML-logo meer als ik inlog op Bestandendelen. Daardoor kan ik geen bestanden uploaden groter dan 2 GB. 

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#40]
Filsender is juist bedoelt voor grote bestanden

**Comment by bartjkdp** [comment]
Ik begrijp niet wat je bedoelt?

**Comment by ziemerink** [comment]
Zie deze vraag! https://www.pleio.nl/questions/view/55577522/html5-functie-in-bestandendelen

**Comment by bartjkdp** [comment]
Ik begrijp hier helemaal niets van. Wat is "geen HTML-logo" Limiet is inderdaad 2GB, groter kan niet.

**Comment by ziemerink** [comment]
Waarom kan het niet groter dan 2GB? H3t is juist bedoelt om grote bestanden te delen!

**Comment by bartjkdp** [comment]
Ik vind 2GB behoorlijk groot. We kunnen pas grotere bestanden verwerken wanneer we de filesender herschrijven. Ik ben daar ooit aan begonnen in Python, maar nog niet afgemaakt. De huidige manier van storage benaderen past niet bij grotere bestanden dan 2GB.

**Comment by ziemerink** [comment]
Hoi Bart, wel vreemd surfnet geeft het volgend eaan:
Configured service constraints

    Maximum recipient addresses per email: Up to 25 email addresses separated by a comma or semi-colon
    Maximum number of files per upload: one - to upload several files in one transaction, compress them into a single archive first
    Maximum file size per upload, with Adobe Flash only: 2 GB
    Maximum file size per upload, with HTML5: 100 GB
    Maximum file / voucher expiry days: 7
