### ISSUE TITLE
Embed tools lijkt op koggenland.pleio.nl niet helemaal goed te werken,  na invoegen van afbeelding wordt deze niet getoond

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#42]
https://koggenland.pleio.nl/blog/view/55364831/test
<img width="877" alt="schermafbeelding 2018-01-24 om 09 42 35" src="https://user-images.githubusercontent.com/1875858/35322538-f6d2625e-00ea-11e8-8672-10295372eccf.png">

**Comment by bartjkdp** [comment]
Ik kan het niet reproduceren. Jij wel?
