### ISSUE TITLE
Error melding Filsender  https://bestandendelen.pleio.nl/simplesamlphp/module.php/core/as_login.php?AuthId=#Spoed pleio-sp&ReturnTo=https://bestandendelen.pleio.nl/filesender/index.php?s=upload

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#45]
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  fopen(/app/log/filesender_2018-01-26_16h.log): failed to open stream: Permission denied in <b>/app/classes/utils/Logger.class.php</b> on line <b>366</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /app/classes/utils/Logger.class.php:366) in <b>/app/classes/rest/RestServer.class.php</b> on line <b>286</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /app/classes/utils/Logger.class.php:366) in <b>/app/classes/rest/RestServer.class.php</b> on line <b>290</b><br />
{"id":5733,"user_id":"ziemerink@www.pleio.nl","user_email":"marcel@pleio.nl","subject":null,"message":null,"created":{"raw":1516984764,"formatted":"26\/01\/2018"},"expires":{"raw":"1517785200","formatted":"04\/02\/2018"},"expiry_date_extension":0,"options":{"get_a_link":false,"add_me_to_recipients":false,"email_me_copies":false,"email_me_on_expire":true,"email_upload_complete":false,"email_download_complete":true,"email_daily_statistics":false,"email_report_on_closing":true,"enable_recipient_email_download_complete":true,"encryption":false},"files":[{"id":13872,"transfer_id":5733,"uid":"d9661e2b-8ec0-a0ee-3070-6e476a8362b2","name":"09 Techniek B.jpg","size":1255962,"sha1":null,"cid":"file_1516984733175_17_1255962_848221"}],"recipients":[{"id":6787,"transfer_id":5733,"token":"f1097eca-0133-747a-7655-d954a5650483","email":"marcel@pleio.nl","created":{"raw":1516984764,"formatted":"26\/01\/2018"},"last_activity":null,"options":null,"download_url":"https:\/\/bestanden-delen.pleio.nl\/?s=download&token=f1097eca-0133-747a-7655-d954a5650483","errors":[]}]}

**Comment by bartjkdp** [comment]
Is gefixt!
