### ISSUE TITLE
Kan het zijn dat Elasticsearch er ui ligt?

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#47]
Krijg van meerdere sites de melding dat er niets meer gevonden wordt! Onder andere https://odrivierenland.pleio.nl/

**Comment by bartjkdp** [comment]
Een van de beheerders heeft de Elasticsearch index gereset. Omdat BIT op 1 database zit wordt dan de index voor iedereen gereset. Het herbouwen duurt ongeveer een uur en heb ik nu gestart...

**Comment by ziemerink** [comment]
De zoek functie werkt nog niet! https://odrivierenland.pleio.nl

**Comment by bartjkdp** [comment]
Kun jij mij even toevoegen op de deelsite als beheerder?

**Comment by ziemerink** [comment]
Done, ik zie bij FFD ook wat raars. Als ik daar op Loon zoek worden er wel resultaten getoond maar er wordt in de balk overal 0 weergeven.
<img width="1516" alt="schermafbeelding 2018-01-30 om 04 56 51" src="https://user-images.githubusercontent.com/1875858/35547566-16e12646-057a-11e8-83b7-3d060dbb4fdf.png">

**Comment by bartjkdp** [comment]
Inmiddels weer opgelost.
