### ISSUE TITLE
Kan gebruiker https://www.pleio.nl/profile/Jean niet verwijderen

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#48]
Ik krijg een blanco pagina als ik deze gebruiker wil verwijderen: https://www.pleio.nl/profile/Jean

**Comment by bartjkdp** [comment]
Er zat aan zijn profiel een ElggCafe (prikbord) object vast van FFD. Die kun je niet verwijderen als de Prikbord plugin niet geladen is. Ik heb de plugin even aangezet op hoofdniveau en toen alsnog de gebruiker verwijderd.
