### ISSUE TITLE
Layout deelsite  linvexo.pleio.nl tekstblokken zijn vreemd

### ISSUE THREAD

**Issue by steenmetzg** [Pleio/pleio#52]
Voorbeeld URL: https://linvexo.pleio.nl/cms/view/55686892/lesmateriaal

De tekstbokken zijn veranderd qua layout. Tekst staat bijv erg geplakt tegen de rand en volgens mij was de layout zoals blogs (met schaduw en zo).

![afbeelding](https://user-images.githubusercontent.com/39088139/45867372-9ef4aa00-bd83-11e8-8e71-dfa57e8442b9.png)

**Comment by ziemerink** [comment]
Verplaatst naar https://gitlab.com/pleio/beheer/issues/662
