### ISSUE TITLE
Installeren Ethercalc

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#6]
Vanuit het team van Tony de vraag gekregen of we een spreadsheet mogelijkheid kunnen aanbieden binnen een groep op bhv.pleio.nl Dit kunnen we doen met Ethercalc. Dus het verzoek om Ethercalc te installeren.

**Comment by bartjkdp** [comment]
Testomgeving opgezet op: https://ethercalc.pleio.nl/ Let op!! alle data wordt naar verloop van tijd weer verwijderd.
