### ISSUE TITLE
Poll bekijken of het nog zinvol; is deze voor het oude template te herschrijven!

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#7]
De intranetredactie kreeg de melding van collega Els de Wit dat er problemen zijn met het aanmaken van een peiling met meer dan 10 keuzemogelijkheden. Ik heb dit zelf getest met een peiling met de vraag 'Wat is jouw favoriete letter uit het alfabet?' waarbij 26 keuzemogelijkheden worden geboden. Zie de bijgevoegde printscreens. Na het opslaan worden slechts 10 keuzes getoond in een volgorde die niet overeenkomt met de volgorde zoals aangemaakt. Als ik de peiling vervolgens wil bewerken, kan ik de volgorde van eerder aangemaakte keuzemogelijkheden niet aanpassen. Voeg ik een mogelijkheid extra toe, dan wordt er na opslaan weer een andere volgorde aan mogelijkheden getoond.

**Comment by bartjkdp** [comment]
Wat mij betreft niet echt zinvol om nu nog op te pakken.
