### ISSUE TITLE
Standaard toegangsniveau in kunnen stellen binnen een groep op ODC / Cloud VPS

### ISSUE THREAD

**Issue by ziemerink** [Pleio/pleio#8]
<img width="940" alt="schermafbeelding 2017-12-21 om 19 52 23" src="https://user-images.githubusercontent.com/1875858/34270508-acd45332-e688-11e7-99e6-da1ca5b5e90c.png">

**Comment by bartjkdp** [comment]
Opgelost in 9ae8968
